### ISSUE TITLE
Unsoundness in `From` implementation

### ISSUE THREAD

**Issue by shinmao** [urschrei/lonlat_bng#19]
### The source of soundness
https://github.com/urschrei/lonlat_bng/blob/c66eca1c878c8d7eb86b53463ccaf56e86dac7bb/src/ffi.rs#L64-L79
With `from` at line 66, we can cast arbitrary type as `Array.data`; with `from` at line 76, we can create a slice of `f64`. It is unsound because there is no any trait bound on `T`, then we can indirectly cast arbitrary types to `f64` slice. `slice::from_raw_parts_mut` requires users to guarantee the data to be valid for reads as `f64` for `len * mem::size_of<T>` bytes[^1] here. If `T` contains padding bytes, then undefined behaviors would occur.

### To reproduce the bug
```rs
#[derive(Copy, Clone)]
struct A {
    a: i8,
    b: i32,
    c: i8,
}

fn main() {
    let mut sa = A { a: 8, b: 9, c: 10 };
    let sa_slice: &mut [A] = &mut [sa];
    let sa_A = Array::from(sa_slice);
    let f64_A: &mut [f64] = sa_A.into();
    println!("{:?}", f64_A);
}
```

[^1]: https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html.

**Comment by urschrei** [comment]
Thanks!

**Comment by shinmao** [comment]
Would you mind report to RUSTSEC advisories so that user can update via cargo audit? Or I can help report it?

**Comment by urschrei** [comment]
I had no idea that unsoundness rose to the level of security advisories, but by all means…

**Comment by shinmao** [comment]
Yes. UB means that we can't guarantee what would happen on any target at anytime. UB should not happen with safe function. In this case, uninitialized memory read might also cause to security issues.
